version: '3'

services:
  mongo:
    image: mongo:4
    container_name: mongo
    restart: always
    ports:
      - '2020:27017'
    volumes:
      - 'mongo:/data/db'

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

volumes:
  mongo: